name: build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt update && sudo apt install -y libblosc-dev
      - uses: dtolnay/rust-toolchain@stable
      - run: rustup component add rustfmt clippy
      - uses: Swatinem/rust-cache@v2
      - run: cargo build  # zarss-ffi tests need build
      - run: cargo test
      - run: cargo check --no-default-features
      - run: cargo fmt --all -- --check
      - run: cargo clippy -- -D warnings

